NOISSUE - Add data collection banner and set circle radius
absmach/callhome pull request #12
Opened 2023-07-10 12:30 UTC by SammyOina

### What does this do?
Adds data collection banner
Sets circle marker radius to 1km

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-07-10 12:31 UTC, dborovcanin approved these changes

2023-07-10 12:32 UTC, dborovcanin requested changes

2023-07-10 13:54 UTC, dborovcanin approved these changes

2023-07-11 11:35 UTC, rodneyosodo approved these changes

2023-07-11 13:24 UTC, drasko approved these changes
LGTM

2023-07-11 13:24 UTC, merged